### ISSUE TITLE
Add bootstrap css?

### ISSUE THREAD

**Issue by harikt** [docmark/docmark#2]
Hi Paul, 

I was having an idea of integrating bootstrap css as the default one. And host http://prismjs.com/ over the https://github.com/docmark/docmark.github.io so it can be served.

See how it looks in the image attached .

![screenshot from 2015-01-22 10 02 16](https://cloud.githubusercontent.com/assets/120454/5850580/014ff4aa-a21e-11e4-857b-302ba09738b3.png)

The left is left blank to add TOC .

If you like I will send a PR :) .

**Comment by pmjones** [comment]
PRs merged. :-)

**Comment by harikt** [comment]
Thanks Paul.
