### ISSUE TITLE
Next heading missing

### ISSUE THREAD

**Issue by harikt** [docmark/docmark#6]
The link is there, but the title is missed.

**Comment by harikt** [comment]
When I checked ContentList , to get the title it was not getting. 

May be the first page is rendered and the next page is not yet rendered. So the next title is always empty.

I set a dummy title at `ContentPage` for there is no title being called.

**Comment by harikt** [comment]
The title are missing only when there are more .md files . If you check the filter it is having the title :/

**Comment by pmjones** [comment]
Yeah, I noticed this last night. The problem is that the "next" page is not actually available yet. I need to change the rendering strategy to work in two passes, not one, so that we have the page information available at the right time.

**Comment by harikt** [comment]
Closing the issue for this project moved to different repo. So this is not relevant any more.
